# Generated by Django 4.0.2 on 2022-02-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_score_song_alter_score_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='author',
        ),
        migrations.RemoveField(
            model_name='score',
            name='song',
        ),
        migrations.RemoveField(
            model_name='song',
            name='author',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
