# Generated by Django 4.0.2 on 2022-02-10 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='Review',
        ),
    ]
